Repository SAP-docs/sapui5, pull requests merged in 2024-08, with the labels that each got.

#149 Update step-10-descriptor-for-applications-8f93bf2.md
  docs/03_Get-Started/step-10-descriptor-for-applications-8f93bf2.md
Labels: contribution, type/examples-samples

#151 Update step-10-descriptor-for-applications-8f93bf2.md
  docs/03_Get-Started/step-10-descriptor-for-applications-8f93bf2.md
Labels: contribution, type/examples-samples

#146 Update enabling-stream-support-b236d32.md
  docs/06_SAP_Fiori_Elements/enabling-stream-support-b236d32.md
Labels: contribution, type/linking, SAP Fiori elements

#152 Update step-27-unit-test-with-qunit-e1ce1de.md
  docs/03_Get-Started/step-27-unit-test-with-qunit-e1ce1de.md
Labels: contribution, type/examples-samples

#154 Update step-26-mock-server-configuration-typescript-3e1c64f.md
  docs/03_Get-Started/step-26-mock-server-configuration-typescript-3e1c64f.md
Labels: contribution, follow-up-with/dev, type/examples-samples

#147 Update descriptor-manifest-json-74038a5.md
  docs/07_APF/descriptor-manifest-json-74038a5.md
Labels: follow-up-with/dev
