Repository SAP-docs/sapui5, pull requests merged in 2024-09, with the labels that each got.

#156 Update step-1-hello-world-typescript-c20489e.md
  docs/03_Get-Started/step-1-hello-world-typescript-c20489e.md
Labels: contribution, type/examples-samples

#143 Update step-4-quick-filter-for-the-worklist-85ec3a9.md
  docs/03_Get-Started/step-4-quick-filter-for-the-worklist-85ec3a9.md
Labels: contribution, follow-up-with/dev, type/outdated

#148 replace ’ with correct single quote (')
  docs/06_SAP_Fiori_Elements/configuring-filter-bars-4bd7590.md
Labels: contribution, SAP Fiori elements

#145 Update step-3-using-dynamic-page-for-the-list-view-0830bce.md
  docs/03_Get-Started/step-3-using-dynamic-page-for-the-list-view-0830bce.md
Labels: contribution, follow-up-with/dev, in-discussion, type/content-gaps

#160 Update using-component-configuration-c264d66.md
  docs/08_Extending_SAPUI5_Applications/using-component-configuration-c264d66.md
Labels: contribution, type/spelling-grammar

#159 Update using-global-side-effects-955ae31.md
  docs/06_SAP_Fiori_Elements/using-global-side-effects-955ae31.md
Labels: contribution, SAP Fiori elements
